title: Bioinformatics Spring School 2021
email: carpentries@otago.ac.nz
baseurl: "/obss-2021-draft/"
url: "https://murraycadzow.github.io"
theme: jekyll-theme-leap-day

workshopPrefix: "/2021-obss-"

